### ISSUE TITLE
not working with next auth v5 @beta 17

### ISSUE THREAD

**Issue by tobimey** [teamhanko/docs#80]
Path: /passkey-api/next-auth

this approach is not working in next auth v5 facing this error:

TypeError: next_auth_providers_credentials__WEBPACK_IMPORTED_MODULE_1__.default.default is not a function
    at PasskeyProvider (webpack-internal:///(rsc)/./node_modules/@teamhanko/passkeys-next-auth-provider/index.js:35:94)
    at eval (webpack-internal:///(rsc)/./auth.ts:32:96)
    at (rsc)/./auth.ts (/Users/tobiasmeyhoefer/Repositories/bitz/.next/server/app/[locale]/page.js:340:1)
    at __webpack_require__ (/Users/tobiasmeyhoefer/Repositories/bitz/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./components/navigation/NavBar.tsx:7:63)
    at (rsc)/./components/navigation/NavBar.tsx (/Users/tobiasmeyhoefer/Repositories/bitz/.next/server/app/[locale]/page.js:362:1)
    at __webpack_require__ (/Users/tobiasmeyhoefer/Repositories/bitz/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./app/[locale]/layout.tsx:13:87)
    at (rsc)/./app/[locale]/layout.tsx (/Users/tobiasmeyhoefer/Repositories/bitz/.next/server/app/[locale]/page.js:318:1)
    at Function.__webpack_require__ (/Users/tobiasmeyhoefer/Repositories/bitz/.next/server/webpack-runtime.js:33:42) {
  type: 'TypeError',
  page: '/en'
}

**Comment by FlxMgdnz** [comment]
Hey @tobiasmeyhoefer did you get it to work? Sorry for the late reply btw.
